// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // ✅ सही API Key जो आपकी JSON फाइल में है
    apiKey: 'AIzaSyBtl7bJE5rNOV3Rd_Zv-ou2ZV-Wf8usHTY',
    appId: '1:88165187266:android:38cadd1e56c716e605c55b',
    messagingSenderId: '88165187266',
    projectId: 'ekamastro-2554d',
    storageBucket: 'ekamastro-2554d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvFuetW6QkDTYs6p-rlj2-KjcD46bQtcs',
    appId: '1:88165187266:android:38cadd1e56c716e605c55b',
    messagingSenderId: '88165187266',
    projectId: 'ekamastro-2554d',
    storageBucket: 'ekamastro-2554d.appspot.com',
    iosBundleId: 'com.ekamastro.astrologer',
  );
}
